[[plugins]]
repo = "mason-org/mason-lspconfig.nvim"

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "mason-org/mason.nvim"
depends = ["mason-lspconfig.nvim", "nvim-lspconfig"]
lua_source = """
require("config.lsp")
"""
