[tools]
node = "24"
bun = "1"
usage = "latest"
yarn = "4"
pnpm = "9"
"npm:@anthropic-ai/claude-code" = "2"
"npm:@openai/codex" = "latest"
"npm:sfw" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
